version: "3.7"

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - CLOUDINARY_URL
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_NAME
    # depends_on:
    #   - db
    # networks:
    #   - my_network
#   db:
#     image: postgres:16-alpine
#     container_name: postgres_db
#     restart: always
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=123
#       - POSTGRES_DB=metablog
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgresql_data:/var/lib/postgresql/data
#       - ./database.sql:/docker-entrypoint-initdb.d/database.sql # Mount the SQL file
#     networks:
#       - my_network
#   adminer:
#     image: adminer:latest
#     container_name: adminer
#     restart: always
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#     networks:
#       - my_network

# networks:
#   my_network:
#     driver: bridge

# volumes:
#   postgresql_data: # กำหนดชื่อ volume ที่ต้องการจะสร้าง
#     driver: local
